name: Build and deploy release manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Clean Build Cache
        run: ./gradlew clean

      - name: Decode Keystore
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo "$SIGNING_KEYSTORE_BASE64" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: Debug Keystore Existence
        run: ls -lah keystore.jks

      - name: Build APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Clean up keystore
        run: rm -f ${{ github.workspace }}/keystore.jks
