name: Build and deploy release manually

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Choose build type (APK or AAB)"
        required: true
        default: "APK"
        type: choice
        options:
          - APK
          - AAB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version code setup
        run: echo "VERSION_CODE=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Clean Build Cache
        run: ./gradlew clean

      - name: Decode Keystore
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo "$SIGNING_KEYSTORE_BASE64" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: Debug Keystore Existence
        run: ls -lah keystore.jks

      - name: Build release
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [[ "${{ github.event.inputs.build_type }}" == "APK" ]]; then
            ./gradlew assembleRelease
          else
            ./gradlew bundleRelease
          fi

      - name: Upload APK to GitHub
        if: ${{ github.event.inputs.build_type == 'APK' }}
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/

      - name: Upload AAB to GitHub
        if: ${{ github.event.inputs.build_type == 'AAB' }}
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Clean up keystore
        run: rm -f ${{ github.workspace }}/keystore.jks
